export const PAYMENT_STATUSES = [
  "PENDING",
  "PARTIALLY_PAID",
  "PAID",
  "ADVANCE_PAID",
  "FULLY_PAID",
  "FAILED",
  "REFUNDED",
];

export const APPOINTMENT_BOOKING_STATUSES = [
  "PENDING_PAYMENT",
  "CONFIRMED",
  "IN_PROGRESS",
  "SERVICE_COMPLETED",
  "FULLY_PAID",
  "CANCELLED",
];

export const BRIDAL_BOOKING_STATUSES = [
  "PENDING_PAYMENT",
  "CONFIRMED",
  "PREPARING",
  "ON_THE_WAY",
  "SERVICE_STARTED",
  "SERVICE_COMPLETED",
  "FULLY_PAID",
  "CANCELLED",
];

export const BRIDAL_EVENT_TYPES = [
  "WEDDING",
  "ENGAGEMENT",
  "RECEPTION",
  "HALDI",
  "MEHENDI",
  "OTHER",
];

export const SERVICE_LOCATIONS = [
  "AT_PARLOUR",
  "AT_HOME",
  "AT_WEDDING_VENUE",
];

export const PAYMENT_METHODS = ["RAZORPAY", "CASH", "MANUAL", "NONE"];
export const PAYMENT_STAGES = ["ADVANCE", "REMAINING"];
export const DISCOUNT_TYPES = ["PERCENTAGE", "FIXED"];
export const BOOKING_TYPES = ["BEAUTY", "BRIDAL"];
export const PAYMENT_PROVIDERS = ["RAZORPAY", "CASH", "MANUAL"];
export const GALLERY_CATEGORIES = [
  "BRIDAL",
  "MAKEUP",
  "HAIR",
  "FACIAL",
  "NAILS",
  "ENGAGEMENT",
  "RECEPTION",
  "BEFORE_AFTER",
];
export const MESSAGE_STATUSES = ["UNREAD", "READ", "RESOLVED"];
export const NOTIFICATION_TYPES = [
  "SYSTEM",
  "NEW_APPOINTMENT",
  "NEW_BRIDAL_BOOKING",
  "CONTACT_MESSAGE",
  "PAYMENT",
  "BOOKING_STATUS",
];
export const AVAILABILITY_TYPES = ["BEAUTY", "BRIDAL"];
